### ISSUE TITLE
CentileBrain Harmonisation

### ISSUE THREAD

**Issue by Bea9619** [CentileBrain/centilebrain#3]
Dear all,

I'm currently using CentileBrain model to obtain z-scores for my subject. However, I noticed that the outputs are not different if I set only one type of scan vendor for all subjects or multiple ones for subjects that actually were scanned with two different scans (so testing whether the volumes are harmonized before calculating the z-scores).
I would ask you how is it possible and if I am making any mistake in the procedure.
I'm compiling your template specifying for the lable "Vendor" "Philips Ingenia"/"Philips Gyroscan Intera", and for the FS version 7.1 or 7.2.
How does the harmonization work?
Many thanks in advance
Sincerely

Beatrice

**Comment by ruiyangge** [comment]
Hi Beatrice,
Thank you for bringing this up. In this case, please set the "SITE" column instead of the "Vendor" column. The harmonization will be performed using ComBatGAM (https://www.sciencedirect.com/science/article/pii/S1053811919310419). 
Best,
Ruiyang

**Comment by Bea9619** [comment]
Hi Ruiyang,
Thank you so much for your reply. It was very helpful. The harmonisation seems to work now that I am using "SITE." Does it also work for different freesurfer versions?
Thank you again
Best,

Beatrice

**Comment by ruiyangge** [comment]
> Hi Ruiyang, Thank you so much for your reply. It was very helpful. The harmonisation seems to work now that I am using "SITE." Does it also work for different freesurfer versions? Thank you again Best,
> 
> Beatrice

Hi Beatrice,
I'm glad to hear it's now working. Regarding the FS versions, we evaluated their impact in our initial paper [https://www.thelancet.com/journals/landig/article/PIIS2589-7500(23)00250-9] and found that different versions have minimal effect on the model performance. Based on this, we believe there’s no need for concern.
Best,
Ruiyang

**Comment by Bea9619** [comment]
Hi Ruiyang,

Thank you again. It sounds perfect!
Best, 

Beatrice
